apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: guard
  name: guard
spec: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: guard-webapp
  name: guard-webapp
  namespace: guard
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: guard-webapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: guard-webapp
    spec:
      containers:
      - image: salamflamo/guard-webapp:latest
        imagePullPolicy: Always
        name: guard-webapp
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: guard-webapp
  name: guard-webapp
  namespace: guard
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: guard-webapp
  sessionAffinity: None
  type: ClusterIP
